# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20160722_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='userimg'),
        ),
    ]
