# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
