# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_user_avatar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
    ]
