# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('music_id', models.BigIntegerField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('marked_num', models.BigIntegerField()),
                ('descript_txt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='playitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist'),
        ),
    ]
