# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playitem',
            name='music_id',
        ),
        migrations.RemoveField(
            model_name='playitem',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='items',
            field=models.ManyToManyField(to='playlist.Playitem'),
        ),
    ]
