# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_remove_user_img'),
        ('music', '0001_initial'),
        ('playlist', '0002_auto_20160726_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='marked_num',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='marked_by',
            field=models.ManyToManyField(related_name='marked_list', to='online.User'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_list', to='online.User'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='music.Track'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='descript_txt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Playitem',
        ),
    ]
