# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
                ('state', models.CharField(choices=[(b'ST', b'ST'), (b'SC', b'SC'), (b'FI', b'FI')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(default=b'', max_length=255)),
                ('track_count', models.IntegerField()),
                ('average_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(db_index=True, max_length=255)),
                ('album', models.CharField(db_index=True, max_length=255)),
                ('albumartist', models.CharField(db_index=True, max_length=255)),
                ('length', models.IntegerField()),
                ('file_path', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('can_poll_for_tracks', 'Can analyze for new tracks in the Music folder'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('title', 'artist', 'album', 'file_path')]),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Track'),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
